apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-0
spec:
  storageClassName: alicloud-nas
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/db/0"
